name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        domain: ["ethda.io", "ethda.app"]
        include:
          - domain: "ethda.io"
            dk_key: DK_ETHDA_IO
          - domain: "ethda.app"
            dk_key: DK_ETHDA_APP

    if: github.repository == 'crustio/ethda-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node v18
        uses: actions/setup-node@v1
        with:
          node-version: v18.18.0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build
        env:
          SITE_URL: "https://docs.${{ matrix.domain }}"

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets[matrix.dk_key] }}
          publish_dir: ./build
          external_repository: crust-pages/docs.${{matrix.domain}}
          cname: "docs.${{matrix.domain}}"
